// Main Bicep template for the Arc demo. Deploys EVERYTHING that can be done
// declaratively. Imperative steps (Arc onboarding, SQL install, agent restarts,
// DCR associations to Arc machines, post-deploy validation) are handled by
// Deploy-ArcDemo.ps1 AFTER this template completes.

targetScope = 'subscription'

@description('Azure region for the demo')
param location string = 'australiaeast'

@description('Resource group for the Arc records, LAW, DCRs, alerts, workbook')
param arcResourceGroup string = 'rg-arc-demo'

@description('Resource group for the backing Azure VMs and infra')
param infraResourceGroup string = 'rg-arc-demo-infra'

@description('Common tags for all resources')
param tags object = {
  owner: 'demo'
  purpose: 'arc-demo'
  costcenter: 'demo'
  env: 'demo'
}

@description('Tenant ID (for Key Vault)')
param tenantId string

@description('Principal ID of the deploying user (for Key Vault RBAC)')
param deployerPrincipalId string

@description('Globally-unique Key Vault name (e.g. kv-arcdemo-xxxxxx)')
param keyVaultName string

@description('Admin username for all VMs')
param adminUsername string = 'azureuser'

@description('Admin password for all VMs (auto-generated by deploy script)')
@secure()
param adminPassword string

@description('Number of Windows VMs (first 2 will host SQL)')
@minValue(1)
@maxValue(20)
param windowsVmCount int = 5

@description('Number of Linux VMs')
@minValue(0)
@maxValue(20)
param linuxVmCount int = 3

@description('VM SKU')
param vmSize string = 'Standard_B2as_v2'

@description('Auto-shutdown time (HHmm)')
param autoShutdownTime string = '1900'

@description('Auto-shutdown timezone (.NET timezone ID)')
param autoShutdownTimezone string = 'Cen. Australia Standard Time'

@description('Email address for budget + alert notifications')
param adminEmail string

@description('Monthly budget amount in subscription currency')
param budgetAmount int = 200

@description('Name prefix for derived resource names (vnet, nsg, ag, alert)')
param namePrefix string = 'arc-demo'

@description('Optional existing NAT Gateway resource ID to attach to the subnet. Pass through from the deploy script so re-runs preserve the Activate-ArcDemo NAT GW attachment. Leave empty on fresh deploys.')
param existingNatGatewayId string = ''

@description('Existing budget start date (YYYY-MM-01) to preserve on re-runs. Defaults to the first of the current UTC month for fresh deploys.')
param existingBudgetStartDate string = utcNow('yyyy-MM-01')

resource rgArc 'Microsoft.Resources/resourceGroups@2024-11-01' = {
  name: arcResourceGroup
  location: location
  tags: tags
}

resource rgInfra 'Microsoft.Resources/resourceGroups@2024-11-01' = {
  name: infraResourceGroup
  location: location
  tags: tags
}

// ----- Workspace + DCRs + alerts (in the Arc RG) -----

module workspaceMod 'modules/workspace.bicep' = {
  name: 'workspace-deploy'
  scope: rgArc
  params: {
    location: location
    tags: tags
    workspaceName: 'law-${namePrefix}'
  }
}

module dcrsMod 'modules/dcrs.bicep' = {
  name: 'dcrs-deploy'
  scope: rgArc
  params: {
    location: location
    tags: tags
    workspaceId: workspaceMod.outputs.workspaceId
    workspaceName: workspaceMod.outputs.workspaceName
  }
}

module alertsMod 'modules/alerts.bicep' = {
  name: 'alerts-deploy'
  scope: rgArc
  params: {
    location: location
    tags: tags
    workspaceId: workspaceMod.outputs.workspaceId
    adminEmail: adminEmail
    namePrefix: namePrefix
  }
}

// ----- Network + KV + VMs (in the Infra RG) -----

module networkMod 'modules/network.bicep' = {
  name: 'network-deploy'
  scope: rgInfra
  params: {
    location: location
    tags: tags
    namePrefix: namePrefix
    existingNatGatewayId: existingNatGatewayId
  }
}

module kvMod 'modules/keyvault.bicep' = {
  name: 'kv-deploy'
  scope: rgInfra
  params: {
    location: location
    tags: tags
    vaultName: keyVaultName
    tenantId: tenantId
    deployerPrincipalId: deployerPrincipalId
  }
}

// Build the VM list. Windows first (so the first 2 become SQL hosts), then Linux.
var winVms = [for i in range(0, windowsVmCount): {
  name: i < 2 ? 'win-sql-0${i + 1}' : 'win-app-0${i - 1}'
  role: i < 2 ? 'sql' : 'app'
  osType: 'Windows'
  publisher: 'MicrosoftWindowsServer'
  offer: 'WindowsServer'
  sku: '2022-datacenter-azure-edition'
}]

var lnxVms = [for i in range(0, linuxVmCount): {
  name: 'lnx-app-0${i + 1}'
  role: 'app'
  osType: 'Linux'
  publisher: 'Canonical'
  offer: '0001-com-ubuntu-server-jammy'
  sku: '22_04-lts-gen2'
}]

var allVms = concat(winVms, lnxVms)

module vmMods 'modules/vm.bicep' = [for vm in allVms: {
  name: 'vm-${vm.name}'
  scope: rgInfra
  params: {
    vmName: vm.name
    location: location
    tags: union(tags, { role: vm.role, ostype: toLower(vm.osType) })
    vmSize: vmSize
    subnetId: networkMod.outputs.subnetId
    adminUsername: adminUsername
    adminPassword: adminPassword
    imagePublisher: vm.publisher
    imageOffer: vm.offer
    imageSku: vm.sku
    osType: vm.osType
    autoShutdownTime: autoShutdownTime
    autoShutdownTimezone: autoShutdownTimezone
  }
}]

// ----- Subscription-scoped pieces -----

module defenderMod 'modules/defender.bicep' = {
  name: 'defender-deploy'
}

module policyMod 'modules/policy.bicep' = {
  name: 'policy-deploy'
  params: {
    location: location
    namePrefix: namePrefix
  }
}

module budgetMod 'modules/budget.bicep' = {
  name: 'budget-deploy'
  params: {
    amount: budgetAmount
    adminEmail: adminEmail
    arcResourceGroup: arcResourceGroup
    infraResourceGroup: infraResourceGroup
    namePrefix: namePrefix
    startDate: existingBudgetStartDate
  }
}

// ----- Outputs -----

output arcResourceGroup string = rgArc.name
output infraResourceGroup string = rgInfra.name
output workspaceId string = workspaceMod.outputs.workspaceId
output workspaceCustomerId string = workspaceMod.outputs.customerId
output keyVaultName string = kvMod.outputs.vaultName
output subnetId string = networkMod.outputs.subnetId
output vmNames array = [for vm in allVms: vm.name]
output dcrCoreId string = dcrsMod.outputs.dcrCoreId
output dcrVmiId string = dcrsMod.outputs.dcrVmiId
output dcrCtId string = dcrsMod.outputs.dcrCtId
output actionGroupId string = alertsMod.outputs.actionGroupId
